# This Dockerfile is not intended to be used as part of the development
# process for the bot - it is the Dockerfile that creates the image
# for `technitaur/tribesbot:base`
#
# If your configuration has different needs, this file is here to make
# your own version of the image. But if you just want to spin up the
# bot as quickly as possible, `Dockerfile` and `docker-compose.yml`
# should be sufficient to get you there.

# syntax=docker/dockerfile:1

FROM debian:stable-slim as debinstall
SHELL [ "/bin/bash", "-c" ]
RUN apt-get update
RUN --mount=type=cache,uid=0,gid=0,target=/var/cache/apt apt-get --yes install python3 python3-venv python3-pip python3-dev libpq-dev libjpeg-dev libffi-dev g++ make vim

FROM debinstall as usersetup
RUN groupadd -g 999 tribesbot
RUN useradd --system --create-home --home-dir /tribesbot -u 999 -g tribesbot tribesbot

FROM usersetup as requirements
WORKDIR /tribesbot
USER tribesbot
COPY requirements.txt .
COPY setup.py .
RUN python3 -m venv .venv
ENV PATH=".venv/bin:$PATH"
RUN pip install --upgrade pip
RUN --mount=type=cache,uid=999,gid=999,target=/tribesbot/.cache/pip pip install -U .

FROM requirements as base
# remove unnecessary packages from the image after everything has been built
USER root
RUN apt-get --yes autoremove python3-venv python3-dev libffi-dev g++ make python3-pip python3-dev
