"""Initial migration

Revision ID: 3390dcbc6934
Revises: 
Create Date: 2021-12-30 21:28:58.338977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3390dcbc6934"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_role",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "finished_game",
        sa.Column("finished_at", sa.DateTime(), nullable=False),
        sa.Column("queue_name", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("win_probability", sa.Float(), nullable=False),
        sa.Column("winning_team", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_finished_game_finished_at"),
        "finished_game",
        ["finished_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_finished_game_queue_name"),
        "finished_game",
        ["queue_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_finished_game_started_at"),
        "finished_game",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_finished_game_winning_team"),
        "finished_game",
        ["winning_team"],
        unique=False,
    )
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(), nullable=True),
        sa.Column("trueskill_mu", sa.Float(), nullable=False),
        sa.Column("trueskill_sigma", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "queue",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_queue_name"), "queue", ["name"], unique=True)
    op.create_table(
        "finished_game_player",
        sa.Column("finished_game_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("player_name", sa.String(), nullable=False),
        sa.Column("team", sa.Integer(), nullable=False),
        sa.Column("trueskill_mu_after", sa.Float(), nullable=False),
        sa.Column("trueskill_mu_before", sa.Float(), nullable=False),
        sa.Column("trueskill_sigma_after", sa.Float(), nullable=False),
        sa.Column("trueskill_sigma_before", sa.Float(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["finished_game_id"],
            ["finished_game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_finished_game_player_finished_game_id"),
        "finished_game_player",
        ["finished_game_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_finished_game_player_player_id"),
        "finished_game_player",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_finished_game_player_player_name"),
        "finished_game_player",
        ["player_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_finished_game_player_team"),
        "finished_game_player",
        ["team"],
        unique=False,
    )
    op.create_table(
        "in_progress_game",
        sa.Column("queue_id", sa.String(), nullable=True),
        sa.Column("win_probability", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["queue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_in_progress_game_created_at"),
        "in_progress_game",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_progress_game_queue_id"),
        "in_progress_game",
        ["queue_id"],
        unique=False,
    )
    op.create_table(
        "queue_player",
        sa.Column("queue_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["queue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("queue_id", "player_id"),
    )
    op.create_index(
        op.f("ix_queue_player_player_id"),
        "queue_player",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_queue_player_queue_id"),
        "queue_player",
        ["queue_id"],
        unique=False,
    )
    op.create_table(
        "queue_role",
        sa.Column("queue_id", sa.String(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["queue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_queue_role_queue_id"),
        "queue_role",
        ["queue_id"],
        unique=False,
    )
    op.create_table(
        "queue_waitlist_player",
        sa.Column("finished_game_id", sa.String(), nullable=False),
        sa.Column("queue_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["finished_game_id"],
            ["finished_game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["queue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("finished_game_id", "queue_id", "player_id"),
    )
    op.create_index(
        op.f("ix_queue_waitlist_player_finished_game_id"),
        "queue_waitlist_player",
        ["finished_game_id"],
        unique=False,
    )
    op.create_table(
        "in_progress_game_channel",
        sa.Column("in_progress_game_id", sa.String(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["in_progress_game_id"],
            ["in_progress_game.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_in_progress_game_channel_in_progress_game_id"),
        "in_progress_game_channel",
        ["in_progress_game_id"],
        unique=False,
    )
    op.create_table(
        "in_progress_game_player",
        sa.Column("in_progress_game_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("team", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["in_progress_game_id"],
            ["in_progress_game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_in_progress_game_player_in_progress_game_id"),
        "in_progress_game_player",
        ["in_progress_game_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_progress_game_player_player_id"),
        "in_progress_game_player",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_progress_game_player_team"),
        "in_progress_game_player",
        ["team"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_in_progress_game_player_team"),
        table_name="in_progress_game_player",
    )
    op.drop_index(
        op.f("ix_in_progress_game_player_player_id"),
        table_name="in_progress_game_player",
    )
    op.drop_index(
        op.f("ix_in_progress_game_player_in_progress_game_id"),
        table_name="in_progress_game_player",
    )
    op.drop_table("in_progress_game_player")
    op.drop_index(
        op.f("ix_in_progress_game_channel_in_progress_game_id"),
        table_name="in_progress_game_channel",
    )
    op.drop_table("in_progress_game_channel")
    op.drop_index(
        op.f("ix_queue_waitlist_player_finished_game_id"),
        table_name="queue_waitlist_player",
    )
    op.drop_table("queue_waitlist_player")
    op.drop_index(op.f("ix_queue_role_queue_id"), table_name="queue_role")
    op.drop_table("queue_role")
    op.drop_index(op.f("ix_queue_player_queue_id"), table_name="queue_player")
    op.drop_index(op.f("ix_queue_player_player_id"), table_name="queue_player")
    op.drop_table("queue_player")
    op.drop_index(
        op.f("ix_in_progress_game_queue_id"), table_name="in_progress_game"
    )
    op.drop_index(
        op.f("ix_in_progress_game_created_at"), table_name="in_progress_game"
    )
    op.drop_table("in_progress_game")
    op.drop_index(
        op.f("ix_finished_game_player_team"), table_name="finished_game_player"
    )
    op.drop_index(
        op.f("ix_finished_game_player_player_name"),
        table_name="finished_game_player",
    )
    op.drop_index(
        op.f("ix_finished_game_player_player_id"),
        table_name="finished_game_player",
    )
    op.drop_index(
        op.f("ix_finished_game_player_finished_game_id"),
        table_name="finished_game_player",
    )
    op.drop_table("finished_game_player")
    op.drop_index(op.f("ix_queue_name"), table_name="queue")
    op.drop_table("queue")
    op.drop_table("player")
    op.drop_index(
        op.f("ix_finished_game_winning_team"), table_name="finished_game"
    )
    op.drop_index(
        op.f("ix_finished_game_started_at"), table_name="finished_game"
    )
    op.drop_index(
        op.f("ix_finished_game_queue_name"), table_name="finished_game"
    )
    op.drop_index(
        op.f("ix_finished_game_finished_at"), table_name="finished_game"
    )
    op.drop_table("finished_game")
    op.drop_table("admin_role")
    # ### end Alembic commands ###
