"""Queue created_at

Revision ID: 757ab2496a9f
Revises: 096161ae8c5a
Create Date: 2021-12-31 10:24:49.802054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "757ab2496a9f"
down_revision = "096161ae8c5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "queue", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_queue_created_at"), "queue", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_queue_created_at"), table_name="queue")
    op.drop_column("queue", "created_at")
    # ### end Alembic commands ###
