"""Add average TS rating

Revision ID: 8e51bdd613e9
Revises: 407bac0e70c7
Create Date: 2021-12-31 17:21:01.542817

"""
import sqlalchemy as sa
from sqlalchemy.sql.expression import text

from alembic import op

# revision identifiers, used by Alembic.
revision = "8e51bdd613e9"
down_revision = "407bac0e70c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "average_trueskill",
                sa.Float(),
                nullable=False,
                server_default=text("0.0"),
            )
        )

    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "average_trueskill",
                sa.Float(),
                nullable=False,
                server_default=text("0.0"),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.drop_column("average_trueskill")

    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.drop_column("average_trueskill")

    # ### end Alembic commands ###
