"""Make custom command name unique

Revision ID: 1fb046cac8b6
Revises: 19a1e9824831
Create Date: 2021-12-31 15:22:28.907717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1fb046cac8b6"
down_revision = "19a1e9824831"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_custom_command_name", table_name="custom_command")
    op.create_index(
        op.f("ix_custom_command_name"), "custom_command", ["name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_custom_command_name"), table_name="custom_command")
    op.create_index(
        "ix_custom_command_name", "custom_command", ["name"], unique=False
    )
    # ### end Alembic commands ###
