"""Add in_progress_game_id to QueueWaitlist

Revision ID: 407bac0e70c7
Revises: 23862e11bc0c
Create Date: 2021-12-31 16:56:58.057379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "407bac0e70c7"
down_revision = "23862e11bc0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_waitlist", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("in_progress_game_id", sa.String(), nullable=False)
        )
        batch_op.drop_constraint(
            "uq_queue_waitlist_finished_game_id", type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_queue_waitlist_finished_game_id"),
            ["finished_game_id"],
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_queue_waitlist_in_progress_game_id"),
            ["in_progress_game_id"],
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_queue_waitlist_in_progress_game_id_in_progress_game"
            ),
            "in_progress_game",
            ["in_progress_game_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_waitlist", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_queue_waitlist_in_progress_game_id_in_progress_game"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("uq_queue_waitlist_in_progress_game_id"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_queue_waitlist_finished_game_id"), type_="unique"
        )
        batch_op.create_unique_constraint(
            "uq_queue_waitlist_finished_game_id",
            ["finished_game_id", "queue_id"],
        )
        batch_op.drop_column("in_progress_game_id")

    # ### end Alembic commands ###
