"""Add player region trueskill

Revision ID: 1a40add2f909
Revises: 94accdcee31d
Create Date: 2022-03-11 18:15:49.413355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a40add2f909"
down_revision = "94accdcee31d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_region_trueskill",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("queue_region_id", sa.String(), nullable=False),
        sa.Column("rated_trueskill_mu", sa.Float(), nullable=False),
        sa.Column("rated_trueskill_sigma", sa.Float(), nullable=False),
        sa.Column("unrated_trueskill_mu", sa.Float(), nullable=False),
        sa.Column("unrated_trueskill_sigma", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
            name=op.f("fk_player_region_trueskill_player_id_player"),
        ),
        sa.ForeignKeyConstraint(
            ["queue_region_id"],
            ["queue_region.id"],
            name=op.f(
                "fk_player_region_trueskill_queue_region_id_queue_region"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_region_trueskill")),
    )
    with op.batch_alter_table(
        "player_region_trueskill", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_player_region_trueskill_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_player_region_trueskill_player_id"),
            ["player_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_player_region_trueskill_queue_region_id"),
            ["queue_region_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "player_region_trueskill", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_player_region_trueskill_queue_region_id")
        )
        batch_op.drop_index(batch_op.f("ix_player_region_trueskill_player_id"))
        batch_op.drop_index(
            batch_op.f("ix_player_region_trueskill_created_at")
        )

    op.drop_table("player_region_trueskill")
    # ### end Alembic commands ###
