"""Add updated_at to current_map

Revision ID: 2f739f9896c9
Revises: 251b0496c201
Create Date: 2022-01-05 22:45:49.216414

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2f739f9896c9"
down_revision = "251b0496c201"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("current_map", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.drop_index("ix_current_map_created_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("current_map", schema=None) as batch_op:
        batch_op.create_index("ix_current_map_created_at", ["created_at"], unique=False)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
