"""Add maps to games

Revision ID: 34fd09e3d34a
Revises: 5c0beea9918b
Create Date: 2022-01-03 17:48:31.347369

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "34fd09e3d34a"
down_revision = "5c0beea9918b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("map_full_name", sa.String(), server_default="", nullable=True)
        )
        batch_op.add_column(
            sa.Column("map_short_name", sa.String(), server_default="", nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_finished_game_map_short_name"),
            ["map_short_name"],
            unique=False,
        )

    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("map_full_name", sa.String(), server_default="", nullable=True)
        )
        batch_op.add_column(
            sa.Column("map_short_name", sa.String(), server_default="", nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_in_progress_game_map_short_name"),
            ["map_short_name"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_in_progress_game_map_short_name"))
        batch_op.drop_column("map_short_name")
        batch_op.drop_column("map_full_name")

    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_finished_game_map_short_name"))
        batch_op.drop_column("map_short_name")
        batch_op.drop_column("map_full_name")

    # ### end Alembic commands ###
