"""Add Queue.is_sweaty column

Revision ID: 89bc36945b56
Revises: e14c46b66983
Create Date: 2022-08-23 17:41:49.761880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89bc36945b56"
down_revision = "e14c46b66983"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finished_game_player", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_finished_game_player_player_name_player", type_="foreignkey"
        )

    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_sweaty",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_column("is_sweaty")

    with op.batch_alter_table("finished_game_player", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_finished_game_player_player_name_player",
            "player",
            ["player_name"],
            ["id"],
        )

    # ### end Alembic commands ###
