"""Remove queue region id unique

Revision ID: 94accdcee31d
Revises: 6081cb6f644f
Create Date: 2022-03-11 18:11:30.765048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "94accdcee31d"
down_revision = "6081cb6f644f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_index("ix_queue_queue_region_id")
        batch_op.create_index(
            batch_op.f("ix_queue_queue_region_id"),
            ["queue_region_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_queue_queue_region_id"))
        batch_op.create_index(
            "ix_queue_queue_region_id", ["queue_region_id"], unique=False
        )

    # ### end Alembic commands ###
