"""Remove AFK votes

Revision ID: 5c0beea9918b
Revises: 6ff3945a5449
Create Date: 2022-01-03 17:11:48.903904

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5c0beea9918b"
down_revision = "6ff3945a5449"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("map_vote", schema=None) as batch_op:
        batch_op.add_column(sa.Column("channel_id", sa.Integer(), nullable=False))

    with op.batch_alter_table("skip_map_vote", schema=None) as batch_op:
        batch_op.add_column(sa.Column("channel_id", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skip_map_vote", schema=None) as batch_op:
        batch_op.drop_column("channel_id")

    with op.batch_alter_table("map_vote", schema=None) as batch_op:
        batch_op.drop_column("channel_id")

    # ### end Alembic commands ###
