"""Add queue regions

Revision ID: 1510d010dbb2
Revises: abf14b87b20f
Create Date: 2022-03-11 17:52:43.833845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1510d010dbb2"
down_revision = "abf14b87b20f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queue_region",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queue_region")),
    )
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("queue_region_id", sa.String(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_queue_queue_region_id"),
            ["queue_region_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_queue_queue_region_id_queue_region"),
            "queue_region",
            ["queue_region_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_queue_queue_region_id_queue_region"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_queue_queue_region_id"))
        batch_op.drop_column("queue_region_id")

    op.drop_table("queue_region")
    # ### end Alembic commands ###
