"""Add rated/unrated trueskill

Revision ID: f16fb3ac6ddb
Revises: 6b0125b388fc
Create Date: 2022-01-03 14:11:30.248843

"""
import sqlalchemy as sa
from sqlalchemy.sql import expression

from alembic import op

# revision identifiers, used by Alembic.
revision = "f16fb3ac6ddb"
down_revision = "6b0125b388fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_rated", sa.Boolean(), nullable=False, server_default=expression.true()))

    with op.batch_alter_table("finished_game_player", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("rated_trueskill_mu_after", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("rated_trueskill_mu_before", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("rated_trueskill_sigma_after", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("rated_trueskill_sigma_before", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("unrated_trueskill_mu_after", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("unrated_trueskill_mu_before", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("unrated_trueskill_sigma_after", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("unrated_trueskill_sigma_before", sa.Float(), nullable=False)
        )
        batch_op.drop_column("trueskill_sigma_before")
        batch_op.drop_column("trueskill_mu_after")
        batch_op.drop_column("trueskill_sigma_after")
        batch_op.drop_column("trueskill_mu_before")

    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rated_trueskill_mu", sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column("rated_trueskill_sigma", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("unrated_trueskill_mu", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("unrated_trueskill_sigma", sa.Float(), nullable=False)
        )
        batch_op.drop_column("trueskill_sigma")
        batch_op.drop_column("trueskill_mu")

    with op.batch_alter_table("player_decay", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("rated_trueskill_mu_before", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("rated_trueskill_mu_after", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("unrated_trueskill_mu_before", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("unrated_trueskill_mu_after", sa.Float(), nullable=False)
        )
        batch_op.drop_column("trueskill_mu_after")
        batch_op.drop_column("trueskill_mu_before")

    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_rated", sa.Boolean(), nullable=False, server_default=expression.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_column("is_rated")

    with op.batch_alter_table("player_decay", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("trueskill_mu_before", sa.FLOAT(), nullable=False)
        )
        batch_op.add_column(sa.Column("trueskill_mu_after", sa.FLOAT(), nullable=False))
        batch_op.drop_column("unrated_trueskill_mu_after")
        batch_op.drop_column("unrated_trueskill_mu_before")
        batch_op.drop_column("rated_trueskill_mu_after")
        batch_op.drop_column("rated_trueskill_mu_before")

    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.add_column(sa.Column("trueskill_mu", sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column("trueskill_sigma", sa.FLOAT(), nullable=False))
        batch_op.drop_column("unrated_trueskill_sigma")
        batch_op.drop_column("unrated_trueskill_mu")
        batch_op.drop_column("rated_trueskill_sigma")
        batch_op.drop_column("rated_trueskill_mu")

    with op.batch_alter_table("finished_game_player", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("trueskill_mu_before", sa.FLOAT(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("trueskill_sigma_after", sa.FLOAT(), nullable=False)
        )
        batch_op.add_column(sa.Column("trueskill_mu_after", sa.FLOAT(), nullable=False))
        batch_op.add_column(
            sa.Column("trueskill_sigma_before", sa.FLOAT(), nullable=False)
        )
        batch_op.drop_column("unrated_trueskill_sigma_before")
        batch_op.drop_column("unrated_trueskill_sigma_after")
        batch_op.drop_column("unrated_trueskill_mu_before")
        batch_op.drop_column("unrated_trueskill_mu_after")
        batch_op.drop_column("rated_trueskill_sigma_before")
        batch_op.drop_column("rated_trueskill_sigma_after")
        batch_op.drop_column("rated_trueskill_mu_before")
        batch_op.drop_column("rated_trueskill_mu_after")

    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.drop_column("is_rated")

    # ### end Alembic commands ###
