"""Make queue region unique

Revision ID: 6081cb6f644f
Revises: 1510d010dbb2
Create Date: 2022-03-11 17:54:23.910643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6081cb6f644f"
down_revision = "1510d010dbb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_index("ix_queue_queue_region_id")
        batch_op.create_index(
            batch_op.f("ix_queue_queue_region_id"),
            ["queue_region_id"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_queue_queue_region_id"))
        batch_op.create_index(
            "ix_queue_queue_region_id", ["queue_region_id"], unique=False
        )

    # ### end Alembic commands ###
