"""Add player decays

Revision ID: 6b0125b388fc
Revises: 98b664abaa96
Create Date: 2022-01-02 21:30:34.407763

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6b0125b388fc"
down_revision = "98b664abaa96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_decay",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("decay_percentage", sa.Float(), nullable=False),
        sa.Column("trueskill_mu_before", sa.Float(), nullable=False),
        sa.Column("trueskill_mu_after", sa.Float(), nullable=False),
        sa.Column("decayed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
            name=op.f("fk_player_decay_player_id_player"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_decay")),
    )
    with op.batch_alter_table("player_decay", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_player_decay_player_id"),
            ["player_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_decay", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_decay_player_id"))

    op.drop_table("player_decay")
    # ### end Alembic commands ###
