"""Fix queue waitlist unique constraint

Revision ID: 251b0496c201
Revises: caf7748ce015
Create Date: 2022-01-05 21:34:05.873239

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "251b0496c201"
down_revision = "caf7748ce015"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_waitlist_player", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_queue_waitlist_player_queue_waitlist_id", type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_queue_waitlist_player_queue_id"),
            ["queue_id", "queue_waitlist_id", "player_id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_waitlist_player", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_queue_waitlist_player_queue_id"), type_="unique"
        )
        batch_op.create_unique_constraint(
            "uq_queue_waitlist_player_queue_waitlist_id",
            ["queue_waitlist_id", "player_id"],
        )

    # ### end Alembic commands ###
