"""Add team names

Revision ID: 98b664abaa96
Revises: 8e51bdd613e9
Create Date: 2022-01-01 12:11:45.350497

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "98b664abaa96"
down_revision = "8e51bdd613e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "team0_name",
                sa.String(),
                server_default="Blood Eagle",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "team1_name",
                sa.String(),
                server_default="Diamond Sword",
                nullable=False,
            )
        )

    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "team0_name",
                sa.String(),
                server_default="Blood Eagle",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "team1_name",
                sa.String(),
                server_default="Diamond Sword",
                nullable=False,
            )
        )
        batch_op.alter_column(
            "average_trueskill",
            existing_type=sa.FLOAT(),
            nullable=True,
            existing_server_default=sa.text("(0.0)"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.alter_column(
            "average_trueskill",
            existing_type=sa.FLOAT(),
            nullable=False,
            existing_server_default=sa.text("(0.0)"),
        )
        batch_op.drop_column("team1_name")
        batch_op.drop_column("team0_name")

    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.drop_column("team1_name")
        batch_op.drop_column("team0_name")

    # ### end Alembic commands ###
