"""Fix queue waitlist

Revision ID: caf7748ce015
Revises: 34fd09e3d34a
Create Date: 2022-01-05 19:30:08.026166

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "caf7748ce015"
down_revision = "34fd09e3d34a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_waitlist_player", schema=None) as batch_op:
        batch_op.add_column(sa.Column("queue_id", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_queue_waitlist_player_queue_id_queue"),
            "queue",
            ["queue_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_waitlist_player", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_queue_waitlist_player_queue_id_queue"),
            type_="foreignkey",
        )
        batch_op.drop_column("queue_id")

    # ### end Alembic commands ###
