"""Add queue region name to finished game

Revision ID: e14c46b66983
Revises: 1a40add2f909
Create Date: 2022-03-11 18:38:57.669272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e14c46b66983"
down_revision = "1a40add2f909"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("queue_region_name", sa.String(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_finished_game_queue_region_name"),
            ["queue_region_name"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_finished_game_queue_region_name"))
        batch_op.drop_column("queue_region_name")

    # ### end Alembic commands ###
