"""Make columns non-null

Revision ID: abf14b87b20f
Revises: 0866b6dffe57
Create Date: 2022-03-07 11:54:06.373725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "abf14b87b20f"
down_revision = "0866b6dffe57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.alter_column(
            "game_id", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("map_vote", schema=None) as batch_op:
        batch_op.alter_column(
            "channel_id", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("skip_map_vote", schema=None) as batch_op:
        batch_op.alter_column(
            "channel_id", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skip_map_vote", schema=None) as batch_op:
        batch_op.alter_column(
            "channel_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("map_vote", schema=None) as batch_op:
        batch_op.alter_column(
            "channel_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.alter_column(
            "game_id", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###
