"""Add is_random and random_probability to maps

Revision ID: 72ee097e1816
Revises: e0ca611b0ef1
Create Date: 2023-09-16 12:39:02.722094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72ee097e1816"
down_revision = "e0ca611b0ef1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("current_map", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_random",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "random_probability",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_random",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "random_probability",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.drop_column("random_probability")
        batch_op.drop_column("is_random")

    with op.batch_alter_table("current_map", schema=None) as batch_op:
        batch_op.drop_column("random_probability")
        batch_op.drop_column("is_random")

    # ### end Alembic commands ###
