"""Add commend table

Revision ID: a5e62a37c44f
Revises: b23a9bcfc0b1
Create Date: 2023-11-11 09:21:35.446949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5e62a37c44f"
down_revision = "b23a9bcfc0b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commend",
        sa.Column("finished_game_id", sa.String(), nullable=False),
        sa.Column("commendee_id", sa.Integer(), nullable=True),
        sa.Column("commendee_name", sa.String(), nullable=False),
        sa.Column("commender_id", sa.Integer(), nullable=True),
        sa.Column("commender_name", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commendee_id"],
            ["player.id"],
            name=op.f("fk_commend_commendee_id_player"),
        ),
        sa.ForeignKeyConstraint(
            ["commender_id"],
            ["player.id"],
            name=op.f("fk_commend_commender_id_player"),
        ),
        sa.ForeignKeyConstraint(
            ["finished_game_id"],
            ["finished_game.id"],
            name=op.f("fk_commend_finished_game_id_finished_game"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commend")),
    )
    with op.batch_alter_table("commend", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_commend_commendee_id"),
            ["commendee_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_commend_commendee_name"),
            ["commendee_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_commend_commender_id"),
            ["commender_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_commend_commender_name"),
            ["commender_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_commend_finished_game_id"),
            ["finished_game_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("commend", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_commend_finished_game_id"))
        batch_op.drop_index(batch_op.f("ix_commend_commender_name"))
        batch_op.drop_index(batch_op.f("ix_commend_commender_id"))
        batch_op.drop_index(batch_op.f("ix_commend_commendee_name"))
        batch_op.drop_index(batch_op.f("ix_commend_commendee_id"))

    op.drop_table("commend")
    # ### end Alembic commands ###
