"""Add queue mu range

Revision ID: 4d8eda11c09e
Revises: f813a3350097
Create Date: 2023-10-27 20:36:34.974334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d8eda11c09e"
down_revision = "f813a3350097"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mu_max", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("mu_min", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_column("mu_min")
        batch_op.drop_column("mu_max")

    # ### end Alembic commands ###
