"""Add leaderboard flag

Revision ID: be8467b2e4f1
Revises: 72ee097e1816
Create Date: 2023-10-25 20:02:28.301454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be8467b2e4f1"
down_revision = "72ee097e1816"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "leaderboard_enabled",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.drop_column("leaderboard_enabled")

    # ### end Alembic commands ###
