"""Fix default

Revision ID: f813a3350097
Revises: be8467b2e4f1
Create Date: 2023-10-25 20:07:08.272651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f813a3350097"
down_revision = "be8467b2e4f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
