"""Add random map names

Revision ID: 72141365cef8
Revises: 82ddb84c9f4c
Create Date: 2023-09-16 11:55:13.169656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72141365cef8"
down_revision = "82ddb84c9f4c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("default_full_name", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("default_short_name", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("rolled_full_name", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("rolled_short_name", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.drop_column("rolled_short_name")
        batch_op.drop_column("rolled_full_name")
        batch_op.drop_column("default_short_name")
        batch_op.drop_column("default_full_name")

    # ### end Alembic commands ###
