"""Add queue ordinal

Revision ID: b23a9bcfc0b1
Revises: 4d8eda11c09e
Create Date: 2023-10-27 21:10:37.047849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b23a9bcfc0b1"
down_revision = "4d8eda11c09e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ordinal",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_column("ordinal")

    # ### end Alembic commands ###
