"""Add raffle tickets

Revision ID: 3fe20acb942a
Revises: 89bc36945b56
Create Date: 2023-08-26 11:08:53.331070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3fe20acb942a"
down_revision = "89bc36945b56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "raffle_tickets",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_player_raffle_tickets"),
            ["raffle_tickets"],
            unique=False,
        )

    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "raffle_ticket_reward",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_rotation_map_raffle_ticket_reward"),
            ["raffle_ticket_reward"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rotation_map_raffle_ticket_reward"))
        batch_op.drop_column("raffle_ticket_reward")

    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_raffle_tickets"))
        batch_op.drop_column("raffle_tickets")

    # ### end Alembic commands ###
