"""Prefix discord models

Revision ID: 402ad305b51b
Revises: fc1d3e3c8384
Create Date: 2024-02-11 13:12:11.084857

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "402ad305b51b"
down_revision = "fc1d3e3c8384"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_guild",
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discord_guild")),
        sa.UniqueConstraint("name", name=op.f("uq_discord_guild_name")),
    )
    with op.batch_alter_table("discord_guild", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_discord_guild_created_at"),
            ["created_at"],
            unique=False,
        )

    op.create_table(
        "discord_member",
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("global_name", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discord_member")),
    )
    with op.batch_alter_table("guild", schema=None) as batch_op:
        batch_op.drop_index("ix_guild_created_at")

    op.drop_table("guild")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild",
        sa.Column("discord_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_guild"),
        sa.UniqueConstraint("name", name="uq_guild_name"),
    )
    with op.batch_alter_table("guild", schema=None) as batch_op:
        batch_op.create_index("ix_guild_created_at", ["created_at"], unique=False)

    op.drop_table("discord_member")
    with op.batch_alter_table("discord_guild", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_discord_guild_created_at"))

    op.drop_table("discord_guild")
    # ### end Alembic commands ###
