"""add message_id to schedule

Revision ID: 14c231a6deb8
Revises: 3f27745fde21
Create Date: 2024-03-24 16:02:43.764984

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "14c231a6deb8"
down_revision = "3f27745fde21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("message_id", sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule", schema=None) as batch_op:
        batch_op.drop_column("message_id")

    # ### end Alembic commands ###
