"""Make game code nullable

Revision ID: 406862e3e08a
Revises: 83bc2f40ee9a
Create Date: 2024-01-24 17:42:12.422804

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "406862e3e08a"
down_revision = "83bc2f40ee9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
