"""Add rated/unrated categories

Revision ID: 56b5aefe3e51
Revises: edfeb9bbe7ed
Create Date: 2024-01-31 22:04:16.968689

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "56b5aefe3e51"
down_revision = "edfeb9bbe7ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_rated", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_column("is_rated")

    # ### end Alembic commands ###
