"""add image_url to map

Revision ID: 7fc0645bb220
Revises: cb84e39b5fd7
Create Date: 2024-06-11 17:59:51.292270

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7fc0645bb220"
down_revision = "cb84e39b5fd7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("map", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("map", schema=None) as batch_op:
        batch_op.drop_column("image_url")

    # ### end Alembic commands ###
