"""Add is_finished to InProgressGame

Revision ID: f283e65712c8
Revises: b4594ec71cc2
Create Date: 2024-02-26 22:36:56.870567

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f283e65712c8"
down_revision = "b4594ec71cc2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_finished", sa.Boolean(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.drop_column("is_finished")

    # ### end Alembic commands ###
