"""Add rotation

Revision ID: bdfe574cd898
Revises: fdd15f1f109a
Create Date: 2024-01-19 00:44:11.797630

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bdfe574cd898"
down_revision = "fdd15f1f109a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_alembic_tmp_queue")
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "rotation_id",
                sa.String(),
                server_default=sa.text("1"),
                nullable=True,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_queue_rotation_id"), ["rotation_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_queue_rotation_id_rotation"),
            "rotation",
            ["rotation_id"],
            ["id"],
        )

    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ordinal",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("rotation_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("map_id", sa.String(), nullable=True))
        batch_op.drop_index("ix_rotation_map_full_name")
        batch_op.drop_index("ix_rotation_map_short_name")
        batch_op.create_index(
            batch_op.f("ix_rotation_map_map_id"), ["map_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_rotation_map_rotation_id"),
            ["rotation_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_rotation_map_rotation_id_rotation"),
            "rotation",
            ["rotation_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_rotation_map_map_id_map"), "map", ["map_id"], ["id"]
        )
        batch_op.drop_column("full_name")
        batch_op.drop_column("short_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.add_column(sa.Column("short_name", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("full_name", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(
            batch_op.f("fk_rotation_map_map_id_map"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_rotation_map_rotation_id_rotation"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_rotation_map_rotation_id"))
        batch_op.drop_index(batch_op.f("ix_rotation_map_map_id"))
        batch_op.create_index(
            "ix_rotation_map_short_name", ["short_name"], unique=False
        )
        batch_op.create_index("ix_rotation_map_full_name", ["full_name"], unique=False)
        batch_op.drop_column("map_id")
        batch_op.drop_column("rotation_id")
        batch_op.drop_column("ordinal")

    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_queue_rotation_id_rotation"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_queue_rotation_id"))
        batch_op.drop_column("rotation_id")

    op.create_table(
        "_alembic_tmp_queue",
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("size", sa.INTEGER(), nullable=False),
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("is_locked", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("is_rated", sa.BOOLEAN(), nullable=False),
        sa.Column(
            "is_isolated",
            sa.BOOLEAN(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("queue_region_id", sa.VARCHAR(), nullable=True),
        sa.Column(
            "is_sweaty",
            sa.BOOLEAN(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("mu_max", sa.FLOAT(), nullable=True),
        sa.Column("mu_min", sa.FLOAT(), nullable=True),
        sa.Column(
            "ordinal",
            sa.INTEGER(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "rotation_id",
            sa.VARCHAR(),
            server_default=sa.text("1"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["queue_region_id"],
            ["queue_region.id"],
            name="fk_queue_queue_region_id_queue_region",
        ),
        sa.ForeignKeyConstraint(
            ["rotation_id"],
            ["rotation.id"],
            name="fk_queue_rotation_id_rotation",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_queue"),
    )
    # ### end Alembic commands ###
