"""fix 2/2: readd queue.rotation_id without default value

Revision ID: f6d467cb25ad
Revises: 265500efca42
Create Date: 2024-01-30 14:45:39.410242

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f6d467cb25ad"
down_revision = "265500efca42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rotation_id", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_queue_rotation_id"), ["rotation_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_queue_rotation_id_rotation"),
            "rotation",
            ["rotation_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_queue_rotation_id_rotation"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_queue_rotation_id"))
        batch_op.drop_column("rotation_id")

    # ### end Alembic commands ###
