"""fix 1/2: remove queue.rotation_id

Revision ID: 265500efca42
Revises: 3178c790cccd
Create Date: 2024-01-30 14:42:25.328963

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "265500efca42"
down_revision = "3178c790cccd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_index("ix_queue_rotation_id")
        batch_op.drop_constraint("fk_queue_rotation_id_rotation", type_="foreignkey")
        batch_op.drop_column("rotation_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "rotation_id",
                sa.VARCHAR(),
                server_default=sa.text("1"),
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            "fk_queue_rotation_id_rotation",
            "rotation",
            ["rotation_id"],
            ["id"],
        )
        batch_op.create_index("ix_queue_rotation_id", ["rotation_id"], unique=False)

    # ### end Alembic commands ###
