"""remove currentmap, add is_next to rotationmap

Revision ID: 70196ad73bdf
Revises: 9730567d125c
Create Date: 2024-01-22 18:19:38.848663

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "70196ad73bdf"
down_revision = "9730567d125c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("current_map")
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_next",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.drop_column("is_next")

    op.create_table(
        "current_map",
        sa.Column("map_rotation_index", sa.INTEGER(), nullable=True),
        sa.Column("full_name", sa.VARCHAR(), nullable=True),
        sa.Column("short_name", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "is_random",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "random_probability",
            sa.INTEGER(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_current_map"),
    )
    # ### end Alembic commands ###
