"""Add stats flag

Revision ID: 9c585d94674d
Revises: a5e62a37c44f
Create Date: 2024-01-16 18:42:28.027172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c585d94674d"
down_revision = "a5e62a37c44f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "stats_enabled",
                sa.Boolean(),
                server_default=sa.text("1"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.drop_column("stats_enabled")

    # ### end Alembic commands ###
