"""Add rotation

Revision ID: 9730567d125c
Revises: fdd15f1f109a
Create Date: 2024-01-21 16:20:08.879089

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9730567d125c"
down_revision = "fdd15f1f109a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rotation",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rotation")),
        sa.UniqueConstraint("name", name=op.f("uq_rotation_name")),
    )
    with op.batch_alter_table("rotation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rotation_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "rotation_id",
                sa.String(),
                server_default=sa.text("1"),
                nullable=True,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_queue_rotation_id"), ["rotation_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_queue_rotation_id_rotation"),
            "rotation",
            ["rotation_id"],
            ["id"],
        )

    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ordinal", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("rotation_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("map_id", sa.String(), nullable=True))
        batch_op.drop_index("ix_rotation_map_full_name")
        batch_op.drop_index("ix_rotation_map_short_name")
        batch_op.create_index(
            batch_op.f("ix_rotation_map_map_id"), ["map_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_rotation_map_ordinal"), ["ordinal"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_rotation_map_rotation_id"),
            ["rotation_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_rotation_map_map_id_map"), "map", ["map_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_rotation_map_rotation_id_rotation"),
            "rotation",
            ["rotation_id"],
            ["id"],
        )
        batch_op.drop_column("full_name")
        batch_op.drop_column("short_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.add_column(sa.Column("short_name", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("full_name", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(
            batch_op.f("fk_rotation_map_rotation_id_rotation"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_rotation_map_map_id_map"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_rotation_map_rotation_id"))
        batch_op.drop_index(batch_op.f("ix_rotation_map_ordinal"))
        batch_op.drop_index(batch_op.f("ix_rotation_map_map_id"))
        batch_op.create_index(
            "ix_rotation_map_short_name", ["short_name"], unique=False
        )
        batch_op.create_index("ix_rotation_map_full_name", ["full_name"], unique=False)
        batch_op.drop_column("map_id")
        batch_op.drop_column("rotation_id")
        batch_op.drop_column("ordinal")

    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_queue_rotation_id_rotation"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_queue_rotation_id"))
        batch_op.drop_column("rotation_id")

    with op.batch_alter_table("rotation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rotation_created_at"))

    op.drop_table("rotation")
    # ### end Alembic commands ###
