"""add min_games_for_leaderboard to category

Revision ID: 6e92fde2c396
Revises: 677c768bdcb5
Create Date: 2024-04-22 17:34:26.336119

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6e92fde2c396"
down_revision = "677c768bdcb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "min_games_for_leaderboard",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_column("min_games_for_leaderboard")

    # ### end Alembic commands ###
