"""make skipmapvote.rotation_id nullable

Revision ID: e838b0504d3b
Revises: 62f85cf1f1d6
Create Date: 2024-02-08 18:28:57.018585

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e838b0504d3b"
down_revision = "62f85cf1f1d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skip_map_vote", schema=None) as batch_op:
        batch_op.alter_column("rotation_id", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_constraint("uq_skip_map_vote_player_id", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_skip_map_vote_player_id"), ["player_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skip_map_vote", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_skip_map_vote_player_id"), type_="unique"
        )
        batch_op.create_unique_constraint(
            "uq_skip_map_vote_player_id", ["player_id", "rotation_id"]
        )
        batch_op.alter_column("rotation_id", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
