"""recreate correct schedule and schedule_player

Revision ID: 485994c1520b
Revises: 4476251e82c3
Create Date: 2024-04-01 17:15:31.789210

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "485994c1520b"
down_revision = "4476251e82c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule",
        sa.Column("day", sa.String(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule")),
        sa.UniqueConstraint("day", "time", name=op.f("uq_schedule_day")),
    )
    op.create_table(
        "schedule_player",
        sa.Column("schedule_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
            name=op.f("fk_schedule_player_player_id_player"),
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedule.id"],
            name=op.f("fk_schedule_player_schedule_id_schedule"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_player")),
        sa.UniqueConstraint(
            "schedule_id",
            "player_id",
            name=op.f("uq_schedule_player_schedule_id"),
        ),
    )
    with op.batch_alter_table("schedule_player", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_schedule_player_player_id"),
            ["player_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_schedule_player_schedule_id"),
            ["schedule_id"],
            unique=False,
        )

    with op.batch_alter_table("in_progress_game_channel", schema=None) as batch_op:
        batch_op.alter_column(
            "in_progress_game_id", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game_channel", schema=None) as batch_op:
        batch_op.alter_column(
            "in_progress_game_id", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("schedule_player", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedule_player_schedule_id"))
        batch_op.drop_index(batch_op.f("ix_schedule_player_player_id"))

    op.drop_table("schedule_player")
    op.drop_table("schedule")
    # ### end Alembic commands ###
