"""Rename voteable_map to map

Revision ID: fdd15f1f109a
Revises: 9c585d94674d
Create Date: 2024-01-19 00:20:43.706962

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fdd15f1f109a"
down_revision = "9c585d94674d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map",
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("short_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_map")),
    )
    with op.batch_alter_table("map", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_map_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_map_full_name"), ["full_name"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_map_short_name"), ["short_name"], unique=True
        )

    with op.batch_alter_table("voteable_map", schema=None) as batch_op:
        batch_op.drop_index("ix_voteable_map_created_at")
        batch_op.drop_index("ix_voteable_map_full_name")
        batch_op.drop_index("ix_voteable_map_short_name")

    with op.batch_alter_table("map_vote", schema=None) as batch_op:
        batch_op.add_column(sa.Column("map_id", sa.String(), nullable=False))
        batch_op.drop_index("ix_map_vote_voteable_map_id")
        batch_op.drop_constraint("uq_map_vote_player_id", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_map_vote_player_id"), ["player_id", "map_id"]
        )
        batch_op.create_index(
            batch_op.f("ix_map_vote_map_id"), ["map_id"], unique=False
        )
        batch_op.drop_constraint(
            "fk_map_vote_voteable_map_id_voteable_map", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_map_vote_map_id_map"), "map", ["map_id"], ["id"]
        )
        batch_op.drop_column("voteable_map_id")
    op.drop_table("voteable_map")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("map_vote", schema=None) as batch_op:
        batch_op.add_column(sa.Column("voteable_map_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_map_vote_map_id_map"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_map_vote_voteable_map_id_voteable_map",
            "voteable_map",
            ["voteable_map_id"],
            ["id"],
        )
        batch_op.drop_index(batch_op.f("ix_map_vote_map_id"))
        batch_op.drop_constraint(batch_op.f("uq_map_vote_player_id"), type_="unique")
        batch_op.create_unique_constraint(
            "uq_map_vote_player_id", ["player_id", "voteable_map_id"]
        )
        batch_op.create_index(
            "ix_map_vote_voteable_map_id", ["voteable_map_id"], unique=False
        )
        batch_op.drop_column("map_id")

    op.create_table(
        "voteable_map",
        sa.Column("full_name", sa.VARCHAR(), nullable=True),
        sa.Column("short_name", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_voteable_map"),
    )
    with op.batch_alter_table("voteable_map", schema=None) as batch_op:
        batch_op.create_index(
            "ix_voteable_map_short_name", ["short_name"], unique=False
        )
        batch_op.create_index("ix_voteable_map_full_name", ["full_name"], unique=False)
        batch_op.create_index(
            "ix_voteable_map_created_at", ["created_at"], unique=False
        )

    with op.batch_alter_table("map", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_map_short_name"))
        batch_op.drop_index(batch_op.f("ix_map_full_name"))
        batch_op.drop_index(batch_op.f("ix_map_created_at"))

    op.drop_table("map")
    # ### end Alembic commands ###
