"""Add Economy Tables

Revision ID: 699eaccdbe40
Revises: fc1d3e3c8384
Create Date: 2024-02-11 23:19:04.470893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "699eaccdbe40"
down_revision = "fc1d3e3c8384"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economy_donation",
        sa.Column("donation_id", sa.String(), nullable=False),
        sa.Column("sending_player_id", sa.Integer(), nullable=False),
        sa.Column("sending_player_name", sa.String(), nullable=False),
        sa.Column("receiving_player_id", sa.Integer(), nullable=False),
        sa.Column("receiving_player_name", sa.String(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receiving_player_id"],
            ["player.id"],
            name=op.f("fk_economy_donation_receiving_player_id_player"),
        ),
        sa.ForeignKeyConstraint(
            ["sending_player_id"],
            ["player.id"],
            name=op.f("fk_economy_donation_sending_player_id_player"),
        ),
        sa.PrimaryKeyConstraint(
            "donation_id", name=op.f("pk_economy_donation")
        ),
    )
    with op.batch_alter_table("economy_donation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_economy_donation_receiving_player_id"),
            ["receiving_player_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_economy_donation_receiving_player_name"),
            ["receiving_player_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_economy_donation_sending_player_id"),
            ["sending_player_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_economy_donation_sending_player_name"),
            ["sending_player_name"],
            unique=False,
        )

    op.create_table(
        "economy_prediction",
        sa.Column("prediction_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(), nullable=False),
        sa.Column("finished_game_id", sa.String(), nullable=True),
        sa.Column("in_progress_game_id", sa.String(), nullable=True),
        sa.Column("team_name", sa.String(), nullable=False),
        sa.Column("prediction_value", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["finished_game_id"],
            ["finished_game.id"],
            name=op.f("fk_economy_prediction_finished_game_id_finished_game"),
        ),
        sa.ForeignKeyConstraint(
            ["in_progress_game_id"],
            ["in_progress_game.id"],
            name=op.f(
                "fk_economy_prediction_in_progress_game_id_in_progress_game"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
            name=op.f("fk_economy_prediction_player_id_player"),
        ),
        sa.PrimaryKeyConstraint(
            "prediction_id", name=op.f("pk_economy_prediction")
        ),
    )
    with op.batch_alter_table("economy_prediction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_economy_prediction_finished_game_id"),
            ["finished_game_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_economy_prediction_in_progress_game_id"),
            ["in_progress_game_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_economy_prediction_player_id"),
            ["player_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_economy_prediction_player_name"),
            ["player_name"],
            unique=False,
        )

    op.create_table(
        "economy_transaction",
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(), nullable=False),
        sa.Column("finished_game_id", sa.String(), nullable=True),
        sa.Column("in_progress_game_id", sa.String(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.String(), nullable=False),
        sa.Column("prediction_id", sa.String(), nullable=True),
        sa.Column("donation_id", sa.String(), nullable=True),
        sa.Column("transaction_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["donation_id"],
            ["economy_donation.donation_id"],
            name=op.f("fk_economy_transaction_donation_id_economy_donation"),
        ),
        sa.ForeignKeyConstraint(
            ["finished_game_id"],
            ["finished_game.id"],
            name=op.f("fk_economy_transaction_finished_game_id_finished_game"),
        ),
        sa.ForeignKeyConstraint(
            ["in_progress_game_id"],
            ["in_progress_game.id"],
            name=op.f(
                "fk_economy_transaction_in_progress_game_id_in_progress_game"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
            name=op.f("fk_economy_transaction_player_id_player"),
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["economy_prediction.prediction_id"],
            name=op.f(
                "fk_economy_transaction_prediction_id_economy_prediction"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "transaction_id", name=op.f("pk_economy_transaction")
        ),
    )
    with op.batch_alter_table("economy_transaction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_economy_transaction_donation_id"),
            ["donation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_economy_transaction_finished_game_id"),
            ["finished_game_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_economy_transaction_in_progress_game_id"),
            ["in_progress_game_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_economy_transaction_player_id"),
            ["player_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_economy_transaction_prediction_id"),
            ["prediction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_economy_transaction_transaction_time"),
            ["transaction_time"],
            unique=False,
        )

    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "currency",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.drop_column("currency")

    with op.batch_alter_table("economy_transaction", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_economy_transaction_transaction_time")
        )
        batch_op.drop_index(batch_op.f("ix_economy_transaction_prediction_id"))
        batch_op.drop_index(batch_op.f("ix_economy_transaction_player_id"))
        batch_op.drop_index(
            batch_op.f("ix_economy_transaction_in_progress_game_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_economy_transaction_finished_game_id")
        )
        batch_op.drop_index(batch_op.f("ix_economy_transaction_donation_id"))

    op.drop_table("economy_transaction")
    with op.batch_alter_table("economy_prediction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_economy_prediction_player_name"))
        batch_op.drop_index(batch_op.f("ix_economy_prediction_player_id"))
        batch_op.drop_index(
            batch_op.f("ix_economy_prediction_in_progress_game_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_economy_prediction_finished_game_id")
        )

    op.drop_table("economy_prediction")
    with op.batch_alter_table("economy_donation", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_economy_donation_sending_player_name")
        )
        batch_op.drop_index(
            batch_op.f("ix_economy_donation_sending_player_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_economy_donation_receiving_player_name")
        )
        batch_op.drop_index(
            batch_op.f("ix_economy_donation_receiving_player_id")
        )

    op.drop_table("economy_donation")
    # ### end Alembic commands ###
