"""fix: remove unique player_id constraint for skipmapvote

Revision ID: 59668fb6ffca
Revises: 532d89c29a5b
Create Date: 2024-01-29 00:45:55.637033

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "59668fb6ffca"
down_revision = "532d89c29a5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skip_map_vote", schema=None) as batch_op:
        batch_op.drop_index("ix_skip_map_vote_player_id")
        batch_op.create_index(
            batch_op.f("ix_skip_map_vote_player_id"),
            ["player_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skip_map_vote", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skip_map_vote_player_id"))
        batch_op.create_index("ix_skip_map_vote_player_id", ["player_id"], unique=False)

    # ### end Alembic commands ###
