"""Convert player id to BigInteger

Revision ID: 2f8bdce07c38
Revises: 196b59d9df5a
Create Date: 2024-02-10 17:59:43.972518

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2f8bdce07c38"
down_revision = "196b59d9df5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
            autoincrement=True,
            existing_server_default=sa.text("nextval('player_id_seq'::regclass)"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
            autoincrement=True,
            existing_server_default=sa.text("nextval('player_id_seq'::regclass)"),
        )

    # ### end Alembic commands ###
