"""add unique constraint to schedule.date_time

Revision ID: 3f27745fde21
Revises: 4400dc81b995
Create Date: 2024-03-22 16:30:48.951355

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3f27745fde21"
down_revision = "4400dc81b995"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_schedule_date_time"), ["date_time"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_schedule_date_time"), type_="unique")

    # ### end Alembic commands ###
