"""create discord channels table

Revision ID: 1a712c98b3d9
Revises: 485994c1520b
Create Date: 2024-04-01 17:51:21.577634

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1a712c98b3d9"
down_revision = "485994c1520b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_channel",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discord_channel")),
        sa.UniqueConstraint("channel_id", name=op.f("uq_discord_channel_channel_id")),
        sa.UniqueConstraint("name", name=op.f("uq_discord_channel_name")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("discord_channel")
    # ### end Alembic commands ###
