"""add unique constraint to schedule_player

Revision ID: 4400dc81b995
Revises: b8420dfaf89e
Create Date: 2024-03-22 15:36:41.278932

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4400dc81b995"
down_revision = "b8420dfaf89e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule_player", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_schedule_player_schedule_id"),
            ["schedule_id", "player_id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule_player", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_schedule_player_schedule_id"), type_="unique"
        )

    # ### end Alembic commands ###
