"""Remove queue regions

Revision ID: fc1d3e3c8384
Revises: 15be96c13e3e
Create Date: 2024-02-11 00:17:47.557134

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fc1d3e3c8384"
down_revision = "15be96c13e3e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("queue_region")
    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.drop_index("ix_finished_game_queue_region_name")
        batch_op.drop_column("queue_region_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "queue_region_name",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.create_index(
            "ix_finished_game_queue_region_name",
            ["queue_region_name"],
            unique=False,
        )

    op.create_table(
        "queue_region",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_queue_region"),
    )
    # ### end Alembic commands ###
