"""Add created_at to categories

Revision ID: 537a7815efa5
Revises: 56b5aefe3e51
Create Date: 2024-01-31 22:08:03.073910

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "537a7815efa5"
down_revision = "56b5aefe3e51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_category_created_at"), ["created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_created_at"))
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
