"""add rotation.is_shuffled

Revision ID: 82125159e75d
Revises: e838b0504d3b
Create Date: 2024-02-09 10:03:23.935327

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "82125159e75d"
down_revision = "e838b0504d3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_shuffled",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation", schema=None) as batch_op:
        batch_op.drop_column("is_shuffled")

    # ### end Alembic commands ###
