"""Add InProgressGame channel_id

Revision ID: d4bd406cc25c
Revises: 4476251e82c3
Create Date: 2024-03-14 15:58:22.937542

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d4bd406cc25c"
down_revision = "4476251e82c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.add_column(sa.Column("channel_id", sa.BigInteger(), nullable=True))

    with op.batch_alter_table("in_progress_game_channel", schema=None) as batch_op:
        batch_op.alter_column(
            "in_progress_game_id", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game_channel", schema=None) as batch_op:
        batch_op.alter_column(
            "in_progress_game_id", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.drop_column("channel_id")

    # ### end Alembic commands ###
