"""rotation end per rotation map

Revision ID: bd43c8eb10a8
Revises: b72721347b16
Create Date: 2024-10-24 16:48:00.745396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd43c8eb10a8"
down_revision = "b72721347b16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "stop_rotation",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.drop_column("stop_rotation")

    # ### end Alembic commands ###
