"""create schedule, schedule_player, and discord_channel tables

Revision ID: b069ccbab75e
Revises: d4bd406cc25c
Create Date: 2024-04-05 18:32:10.979167

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b069ccbab75e"
down_revision = "d4bd406cc25c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_channel",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discord_channel")),
        sa.UniqueConstraint("channel_id", name=op.f("uq_discord_channel_channel_id")),
        sa.UniqueConstraint("name", name=op.f("uq_discord_channel_name")),
    )
    op.create_table(
        "schedule",
        sa.Column("day", sa.String(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule")),
        sa.UniqueConstraint("day", "time", name=op.f("uq_schedule_day")),
    )
    op.create_table(
        "schedule_player",
        sa.Column("schedule_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
            name=op.f("fk_schedule_player_player_id_player"),
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedule.id"],
            name=op.f("fk_schedule_player_schedule_id_schedule"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_player")),
        sa.UniqueConstraint(
            "schedule_id",
            "player_id",
            name=op.f("uq_schedule_player_schedule_id"),
        ),
    )
    with op.batch_alter_table("schedule_player", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_schedule_player_player_id"),
            ["player_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_schedule_player_schedule_id"),
            ["schedule_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule_player", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedule_player_schedule_id"))
        batch_op.drop_index(batch_op.f("ix_schedule_player_player_id"))

    op.drop_table("schedule_player")
    op.drop_table("schedule")
    op.drop_table("discord_channel")
    # ### end Alembic commands ###
