"""add added_at to queue_player

Revision ID: cb84e39b5fd7
Revises: 6913629c7ee5
Create Date: 2024-05-30 15:10:07.030114

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cb84e39b5fd7"
down_revision = "6913629c7ee5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_player", schema=None) as batch_op:
        batch_op.add_column(sa.Column("added_at", sa.DateTime(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_queue_player_added_at"), ["added_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_player", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_queue_player_added_at"))
        batch_op.drop_column("added_at")

    # ### end Alembic commands ###
