"""rename rotation.is_shuffled to is_random

Revision ID: 196b59d9df5a
Revises: 82125159e75d
Create Date: 2024-02-10 12:49:33.786479

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "196b59d9df5a"
down_revision = "82125159e75d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_random",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )
        batch_op.drop_column("is_shuffled")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_shuffled",
                sa.BOOLEAN(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )
        batch_op.drop_column("is_random")

    # ### end Alembic commands ###
