"""make admin_role.role_id BigInt

Revision ID: 6913629c7ee5
Revises: eac69ad70805
Create Date: 2024-05-21 11:51:15.907800

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6913629c7ee5"
down_revision = "eac69ad70805"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin_role", schema=None) as batch_op:
        batch_op.alter_column(
            "role_id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("admin_role", schema=None) as batch_op:
        batch_op.alter_column(
            "role_id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
