"""Add game code

Revision ID: 83bc2f40ee9a
Revises: 9c585d94674d
Create Date: 2024-01-24 17:39:37.802033

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "83bc2f40ee9a"
down_revision = "9c585d94674d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.add_column(sa.Column("code", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.drop_column("code")

    # ### end Alembic commands ###
