"""update vote models to use rotation

Revision ID: 532d89c29a5b
Revises: f2ec4d7c17a9
Create Date: 2024-01-26 11:33:54.018583

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "532d89c29a5b"
down_revision = "f2ec4d7c17a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("map_vote", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rotation_map_id", sa.String(), nullable=False))
        batch_op.drop_index("ix_map_vote_map_id")
        batch_op.drop_constraint("uq_map_vote_player_id", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_map_vote_player_id"),
            ["player_id", "rotation_map_id"],
        )
        batch_op.create_index(
            batch_op.f("ix_map_vote_rotation_map_id"),
            ["rotation_map_id"],
            unique=False,
        )
        batch_op.drop_constraint("fk_map_vote_map_id_map", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_map_vote_rotation_map_id_rotation_map"),
            "rotation_map",
            ["rotation_map_id"],
            ["id"],
        )
        batch_op.drop_column("map_id")

    with op.batch_alter_table("skip_map_vote", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rotation_id", sa.String(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_skip_map_vote_rotation_id"),
            ["rotation_id"],
            unique=False,
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_skip_map_vote_player_id"),
            ["player_id", "rotation_id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_skip_map_vote_rotation_id_rotation"),
            "rotation",
            ["rotation_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skip_map_vote", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_skip_map_vote_rotation_id_rotation"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("uq_skip_map_vote_player_id"), type_="unique"
        )
        batch_op.drop_index(batch_op.f("ix_skip_map_vote_rotation_id"))
        batch_op.drop_column("rotation_id")

    with op.batch_alter_table("map_vote", schema=None) as batch_op:
        batch_op.add_column(sa.Column("map_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_map_vote_rotation_map_id_rotation_map"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key("fk_map_vote_map_id_map", "map", ["map_id"], ["id"])
        batch_op.drop_index(batch_op.f("ix_map_vote_rotation_map_id"))
        batch_op.drop_constraint(batch_op.f("uq_map_vote_player_id"), type_="unique")
        batch_op.create_unique_constraint(
            "uq_map_vote_player_id", ["player_id", "map_id"]
        )
        batch_op.create_index("ix_map_vote_map_id", ["map_id"], unique=False)
        batch_op.drop_column("rotation_map_id")

    # ### end Alembic commands ###
