"""add random rotation weight

Revision ID: b72721347b16
Revises: 7fc0645bb220
Create Date: 2024-10-20 20:59:50.590340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b72721347b16"
down_revision = "7fc0645bb220"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "random_weight",
                sa.Integer(),
                server_default=sa.text("1"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation_map", schema=None) as batch_op:
        batch_op.drop_column("random_weight")

    # ### end Alembic commands ###
