"""block maps for random rotation

Revision ID: 4aa167bcf1b8
Revises: bd43c8eb10a8
Create Date: 2024-10-27 10:28:42.078634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4aa167bcf1b8"
down_revision = "bd43c8eb10a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rotation_map_history",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rotation_id", sa.String(), nullable=True),
        sa.Column("rotation_map_id", sa.String(), nullable=True),
        sa.Column(
            "selected_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rotation_id"],
            ["rotation.id"],
            name=op.f("fk_rotation_map_history_rotation_id_rotation"),
        ),
        sa.ForeignKeyConstraint(
            ["rotation_map_id"],
            ["rotation_map.id"],
            name=op.f("fk_rotation_map_history_rotation_map_id_rotation_map"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rotation_map_history")),
    )
    with op.batch_alter_table("rotation_map_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rotation_map_history_rotation_id"),
            ["rotation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_rotation_map_history_rotation_map_id"),
            ["rotation_map_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_rotation_map_history_selected_at"),
            ["selected_at"],
            unique=False,
        )

    with op.batch_alter_table("rotation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "min_maps_before_requeue",
                sa.Integer(),
                server_default=sa.text("1"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "weight_increase",
                sa.Float(),
                server_default=sa.text("(0.0)"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotation", schema=None) as batch_op:
        batch_op.drop_column("weight_increase")
        batch_op.drop_column("min_maps_before_requeue")

    with op.batch_alter_table("rotation_map_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rotation_map_history_selected_at"))
        batch_op.drop_index(
            batch_op.f("ix_rotation_map_history_rotation_map_id")
        )
        batch_op.drop_index(batch_op.f("ix_rotation_map_history_rotation_id"))

    op.drop_table("rotation_map_history")
    # ### end Alembic commands ###
