"""Remove unrated

Revision ID: 15be96c13e3e
Revises: 194f35739989
Create Date: 2024-02-10 23:57:13.345059

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "15be96c13e3e"
down_revision = "194f35739989"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finished_game_player", schema=None) as batch_op:
        batch_op.drop_column("unrated_trueskill_mu_before")
        batch_op.drop_column("unrated_trueskill_sigma_after")
        batch_op.drop_column("unrated_trueskill_sigma_before")
        batch_op.drop_column("unrated_trueskill_mu_after")

    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.drop_column("unrated_trueskill_sigma")
        batch_op.drop_column("unrated_trueskill_mu")

    with op.batch_alter_table("player_decay", schema=None) as batch_op:
        batch_op.drop_column("unrated_trueskill_mu_before")
        batch_op.drop_column("unrated_trueskill_mu_after")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_decay", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "unrated_trueskill_mu_after",
                postgresql.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "unrated_trueskill_mu_before",
                postgresql.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "unrated_trueskill_mu",
                postgresql.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "unrated_trueskill_sigma",
                postgresql.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("finished_game_player", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "unrated_trueskill_mu_after",
                postgresql.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "unrated_trueskill_sigma_before",
                postgresql.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "unrated_trueskill_sigma_after",
                postgresql.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "unrated_trueskill_mu_before",
                postgresql.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
