"""Make role_id bigint

Revision ID: 4aa167bcf1b8
Revises: e64a149b226f
Create Date: 2025-06-07 18:19:32.272390

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "54080d3503e2"
down_revision = "e64a149b226f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_role", schema=None) as batch_op:
        batch_op.alter_column(
            "role_id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_role", schema=None) as batch_op:
        batch_op.alter_column(
            "role_id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
