"""Add position short name

Revision ID: 12d80f7132bd
Revises: e1275372f19a
Create Date: 2025-06-07 22:22:38.845679

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "12d80f7132bd"
down_revision = "e1275372f19a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("position", schema=None) as batch_op:
        batch_op.add_column(sa.Column("short_name", sa.String(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_position_short_name"), ["short_name"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("position", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_position_short_name"))
        batch_op.drop_column("short_name")

    # ### end Alembic commands ###
