"""Add position references

Revision ID: e1275372f19a
Revises: 7d5d0da1c412
Create Date: 2025-06-07 21:41:34.399500

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e1275372f19a"
down_revision = "7d5d0da1c412"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finished_game_player", schema=None) as batch_op:
        batch_op.add_column(sa.Column("position_name", sa.String(), nullable=True))

    with op.batch_alter_table("in_progress_game_player", schema=None) as batch_op:
        batch_op.add_column(sa.Column("position_id", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_in_progress_game_player_position_id"),
            ["position_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_in_progress_game_player_position_id_position"),
            "position",
            ["position_id"],
            ["id"],
        )

    with op.batch_alter_table("player_category_trueskill", schema=None) as batch_op:
        batch_op.add_column(sa.Column("position_id", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_player_category_trueskill_position_id"),
            ["position_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_player_category_trueskill_position_id_position"),
            "position",
            ["position_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_category_trueskill", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_player_category_trueskill_position_id_position"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_player_category_trueskill_position_id"))
        batch_op.drop_column("position_id")

    with op.batch_alter_table("in_progress_game_player", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_in_progress_game_player_position_id_position"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_in_progress_game_player_position_id"))
        batch_op.drop_column("position_id")

    with op.batch_alter_table("finished_game_player", schema=None) as batch_op:
        batch_op.drop_column("position_name")

    # ### end Alembic commands ###
