"""Add per-queue map trueskill

Revision ID: df567a3b347f
Revises: 264c3c597e8c
Create Date: 2025-06-15 12:57:11.798726

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "df567a3b347f"
down_revision = "264c3c597e8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "map_trueskill_enabled",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_column("map_trueskill_enabled")

    # ### end Alembic commands ###
