"""Add config model

Revision ID: 9ec524cf9bb8
Revises: 12d80f7132bd
Create Date: 2025-06-11 20:26:20.311894

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9ec524cf9bb8"
down_revision = "12d80f7132bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column(
            "default_trueskill_mu",
            sa.Float(),
            server_default=sa.text("25.0"),
            nullable=False,
        ),
        sa.Column(
            "default_trueskill_sigma",
            sa.Float(),
            server_default=sa.text("8.333"),
            nullable=False,
        ),
        sa.Column(
            "default_trueskill_tau",
            sa.Float(),
            server_default=sa.text("0.0833"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_config")),
    )
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_config_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_config_updated_at"), ["updated_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_config_updated_at"))
        batch_op.drop_index(batch_op.f("ix_config_created_at"))

    op.drop_table("config")
    # ### end Alembic commands ###
