"""Add map_id to in_progress_game model

Revision ID: 264c3c597e8c
Revises: ca13ce582ac0
Create Date: 2025-06-14 18:10:33.636467

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "264c3c597e8c"
down_revision = "ca13ce582ac0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.add_column(sa.Column("map_id", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_in_progress_game_map_id"), ["map_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_in_progress_game_map_id_map"),
            "map",
            ["map_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_in_progress_game_map_id_map"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_in_progress_game_map_id"))
        batch_op.drop_column("map_id")

    # ### end Alembic commands ###
