"""Add flag for position based trueskill

Revision ID: edab91ede0b2
Revises: 9ec524cf9bb8
Create Date: 2025-06-12 19:24:19.703791

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "edab91ede0b2"
down_revision = "9ec524cf9bb8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "enable_position_trueskill",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.drop_column("enable_position_trueskill")

    # ### end Alembic commands ###
