"""Add queue position model

Revision ID: 7d5d0da1c412
Revises: 28826c0d6fff
Create Date: 2025-06-07 18:48:20.238663

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7d5d0da1c412"
down_revision = "28826c0d6fff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queue_position",
        sa.Column("queue_id", sa.String(), nullable=False),
        sa.Column("position_id", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.id"],
            name=op.f("fk_queue_position_position_id_position"),
        ),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["queue.id"],
            name=op.f("fk_queue_position_queue_id_queue"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queue_position")),
        sa.UniqueConstraint(
            "queue_id", "position_id", name=op.f("uq_queue_position_queue_id")
        ),
    )
    with op.batch_alter_table("queue_position", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_queue_position_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_queue_position_position_id"),
            ["position_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_queue_position_queue_id"),
            ["queue_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_position", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_queue_position_queue_id"))
        batch_op.drop_index(batch_op.f("ix_queue_position_position_id"))
        batch_op.drop_index(batch_op.f("ix_queue_position_created_at"))

    op.drop_table("queue_position")
    # ### end Alembic commands ###
