"""Change queue mu min/max to rank min/max

Revision ID: e673b49d7c2f
Revises: df567a3b347f
Create Date: 2025-09-10 11:05:52.638238

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e673b49d7c2f"
down_revision = "df567a3b347f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rank_max", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("rank_min", sa.Float(), nullable=True))
        batch_op.drop_column("mu_min")
        batch_op.drop_column("mu_max")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "mu_max",
                postgresql.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "mu_min",
                postgresql.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("rank_min")
        batch_op.drop_column("rank_max")

    # ### end Alembic commands ###
