"""Add map-based trueskill

Revision ID: ca13ce582ac0
Revises: edab91ede0b2
Create Date: 2025-06-12 19:45:14.745230

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ca13ce582ac0"
down_revision = "edab91ede0b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "enable_map_trueskill",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )

    with op.batch_alter_table("player_category_trueskill", schema=None) as batch_op:
        batch_op.add_column(sa.Column("map_id", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_player_category_trueskill_map_id"),
            ["map_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_player_category_trueskill_map_id_map"),
            "map",
            ["map_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_category_trueskill", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_player_category_trueskill_map_id_map"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_player_category_trueskill_map_id"))
        batch_op.drop_column("map_id")

    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.drop_column("enable_map_trueskill")

    # ### end Alembic commands ###
