"""Add captain pick mode

Revision ID: 3e91c894b0a8
Revises: e673b49d7c2f
Create Date: 2026-04-25 15:38:32.608532

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3e91c894b0a8"
down_revision = "e673b49d7c2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "draft_pick",
        sa.Column("in_progress_game_id", sa.String(), nullable=False),
        sa.Column("pick_number", sa.Integer(), nullable=False),
        sa.Column("captain_player_id", sa.BigInteger(), nullable=False),
        sa.Column("picked_player_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["captain_player_id"],
            ["player.id"],
            name=op.f("fk_draft_pick_captain_player_id_player"),
        ),
        sa.ForeignKeyConstraint(
            ["in_progress_game_id"],
            ["in_progress_game.id"],
            name=op.f("fk_draft_pick_in_progress_game_id_in_progress_game"),
        ),
        sa.ForeignKeyConstraint(
            ["picked_player_id"],
            ["player.id"],
            name=op.f("fk_draft_pick_picked_player_id_player"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_draft_pick")),
        sa.UniqueConstraint(
            "in_progress_game_id",
            "pick_number",
            name=op.f("uq_draft_pick_in_progress_game_id"),
        ),
    )
    with op.batch_alter_table("draft_pick", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_draft_pick_captain_player_id"),
            ["captain_player_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_draft_pick_in_progress_game_id"),
            ["in_progress_game_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_draft_pick_picked_player_id"),
            ["picked_player_id"],
            unique=False,
        )

    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("captain_channel_id", sa.BigInteger(), nullable=True)
        )

    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_captain_pick",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_finished_game_is_captain_pick"),
            ["is_captain_pick"],
            unique=False,
        )

    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_drafting",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_in_progress_game_is_drafting"),
            ["is_drafting"],
            unique=False,
        )

    with op.batch_alter_table("in_progress_game_player", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_captain",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )
        batch_op.alter_column("team", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_captain_pick",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_queue_is_captain_pick"),
            ["is_captain_pick"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_queue_is_captain_pick"))
        batch_op.drop_column("is_captain_pick")

    with op.batch_alter_table("in_progress_game_player", schema=None) as batch_op:
        batch_op.alter_column("team", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("is_captain")

    with op.batch_alter_table("in_progress_game", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_in_progress_game_is_drafting"))
        batch_op.drop_column("is_drafting")

    with op.batch_alter_table("finished_game", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_finished_game_is_captain_pick"))
        batch_op.drop_column("is_captain_pick")

    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.drop_column("captain_channel_id")

    with op.batch_alter_table("draft_pick", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_draft_pick_picked_player_id"))
        batch_op.drop_index(batch_op.f("ix_draft_pick_in_progress_game_id"))
        batch_op.drop_index(batch_op.f("ix_draft_pick_captain_player_id"))

    op.drop_table("draft_pick")
    # ### end Alembic commands ###
